name: Auto check new version and modify fonts
on:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  check-noto-version:
    runs-on: ubuntu-latest
    outputs:
      sans: ${{ steps.noto-sans-cjk.outputs.version }}
    steps:
      - id: noto-sans-cjk
        run: |
          echo 'sans_commit_info<<EOF' >> $GITHUB_ENV
          curl -H 'Accept: application/vnd.github.v3+json' \
          https://api.github.com/repos/googlefonts/noto-cjk/commits?path=Sans&per_page=1 \
          >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - run: echo "${{ env.sans_commit_info }}"
