name: Auto check new version and modify fonts
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  check-noto-version:
    runs-on: ubuntu-latest
    outputs:
      local: ${{ steps.get-aosp-sans-commit.outputs.commit }}
      remote: ${{ steps.get-noto-sans-commit.outputs.commit }}
    steps:
      - uses: actions/checkout@v2
      - id: get-aosp-sans-commit
        run: |
          echo 'local_sans_commit<<EOF' >> $GITHUB_ENV
          echo ./Sans/commit_sha.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo "::set-output name=local::$env.local_sans_commit"
      - name: Fetch commit info from GitHub API
        run: |
          echo 'remote_sans_commit_info<<EOF' >> $GITHUB_ENV
          curl -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/googlefonts/noto-cjk/commits?path=Sans&per_page=1" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - id: get-noto-sans-commit
        run: |
          echo 'remote_sans_commit<<EOF' >> $GITHUB_ENV
          echo "${{ fromJSON(env.remote_sans_commit_info)[0].commit.tree.sha }}" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo "::set-output name=commit::$env.remote_sans_commit"
  modify-noto:
    needs: check-noto-version
    runs-on: ubuntu-latest
    if: ${{ needs.check-noto-version.outputs.remote != needs.check-noto-version.outputs.local }}
    steps:
      - run: echo "${{ needs.check-noto-version.outputs.remote }}"
