name: Auto check new version and modify fonts
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  modify-sans:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: get-aosp-sans-commit
        run: |
          echo 'local_sans_commit<<EOF' >> $GITHUB_ENV
          cat ./Sans/commit_sha.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Fetch commit info from GitHub API
        run: |
          echo 'remote_sans_commit_info<<EOF' >> $GITHUB_ENV
          curl -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/googlefonts/noto-cjk/commits?path=Sans&per_page=1" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - id: get-noto-sans-commit
        run: |
          echo 'remote_sans_commit<<EOF' >> $GITHUB_ENV
          echo "${{ fromJSON(env.remote_sans_commit_info)[0].commit.tree.sha }}" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: make a temp folder
        run: |
          mkdir ./tmp
          mkdir ./tmp/aosp-noto-script
      # TODO: comapre serif commit sha
      - id: get-toolchains
        if: ${{ env.local_sans_commit != env.remote_sans_commit }}
        run: |
          curl "https://android.googlesource.com/platform/external/noto-fonts/+/refs/heads/android11-qpr2-release/cjk/subset_noto_cjk.py?format=TEXT" \
          | base64 --decode > subset_noto_cjk.py
          cat subset_noto_cjk.py
        working-directory: ./tmp/aosp-noto-script
